const constants = {
  HOT_SELLING_PRODUCTS: 'HOT_SELLING_PRODUCTS',
  HOT_SELLING_PRODUCTS_ERROR: 'HOT_SELLING_PRODUCTS_ERROR',
  DISCOUNT_ITEMS: 'DISCOUNT_ITEMS',
  DISCOUNT_ITEMS_ERROR: 'DISCOUNT_ITEMS_ERROR',
};

export default constants;
