const constants = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  ALL_PRODUCTS_ERROR: 'ALL_PRODUCTS_ERROR',
  ONE_PRODUCT: 'ONE_PRODUCT',
  ONE_PRODUCT_ERROR: 'ONE_PRODUCT_ERROR',
  NEW_RATING: 'NEW_RATING',
  SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  SUBMIT_REVIEW_ERROR: 'SUBMIT_REVIEW_ERROR',
  ALL_REVIEWS: 'ALL_REVIEWS',
  CART: 'CART',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
};

export default constants;
