const constants = {
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SHOW_MODAL: 'SHOW_MODAL',
  LOADER: 'LOADER',
  LOGGED_IN_USER: 'LOGGED_IN_USER',
  LOGGED_IN_USER_ERROR: 'LOGGED_IN_USER_ERROR',
};

export default constants;
